name: Website Deployment

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.426  # Replace with your .NET Core version

      - name: Build and Publish ASP.NET Core App
        run: |
          dotnet build
          dotnet publish -c Release -o ./publish
        working-directory: Website  # Specify your project folder
