name: Website Deployment

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.426  # Replace with your .NET Core version

      - name: Build
        run: |
          cd ../Website
          dotnet build
        working-directory: Website

      - name: Publish
        run: |
          cd ../Website
          dotnet publish -c Release -o ../../publish
        working-directory: Website

      - name: Deployment
        run: |
          cd ../../publish
          git init
          git add .
          git commit -m "Deployment"
          git branch -M gh-pages
          git remote add origin https://github.com:KhizaroOo/khizooo-web-core3.1.git
          git push -f -u origin gh-pages
        working-directory: publish

